package Model;

import Controller.ConfiguracoesController;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.util.ArrayList;

public class BarChartPanel extends JPanel {

    private DefaultCategoryDataset dataset;
    private ConfiguracoesController config = new ConfiguracoesController();

    public BarChartPanel(ArrayList<AsteroidesPorPeriodo> asteroidesPorPeriodo) {
        initComponents();
        String periodoDisplay = config.consultarPeridoDoGrafico();

        // Create initial dataset with provided data
        dataset = new DefaultCategoryDataset();
        for (AsteroidesPorPeriodo periodo : asteroidesPorPeriodo) {
            dataset.addValue(periodo.getNumeroPorMes(), "Asteroides", periodo.getPeriodo());
        }

        // Create initial bar chart
        JFreeChart chart = ChartFactory.createBarChart(
                "Frequência de Asteroides por " + periodoDisplay, // chart title
                periodoDisplay, // x-axis label
                "Número de Asteroides", // y-axis label
                dataset, // data
                PlotOrientation.VERTICAL, // orientation
                true, // include legend
                true, // tooltips
                false // URLs (not used here)
        );

        // Criar o painel de gráfico e adicionar ao JPanel
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        this.setLayout(new BorderLayout());
        this.add(chartPanel, BorderLayout.CENTER);
    }

    // Method to update chart data
    public void updateData(ArrayList<AsteroidesPorPeriodo> asteroidesPorPeriodo) {
        // Clear existing data
        dataset.clear();

        // Add new data to dataset
        for (AsteroidesPorPeriodo periodo : asteroidesPorPeriodo) {
            dataset.addValue(periodo.getNumeroPorMes(), "Asteroides", periodo.getPeriodo());
        }
    }

    // Method generated by NetBeans for component initialization
    private void initComponents() {
        // Additional components can be initialized here if necessary
    }
}
